---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cray-{{ template "cray-certmanager.fullname" . }}-hook-cluster-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cray-{{ template "cray-certmanager.fullname" . }}-hook-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: cray-{{ template "cray-certmanager.fullname" . }}-hook
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cray-{{ template "cray-certmanager.fullname" . }}-hook-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cray-{{ template "cray-certmanager.fullname" . }}-hook