---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager
rules:
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [get, patch]
  - apiGroups: ["", "apps"]
    resources: ["pods", "deployments"]
    verbs: ["get", "list", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cert-manager
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cert-manager
  namespace: {{ .Release.Namespace }}
