apiVersion: v2
name: cray-certmanager-issuers
version: 0.6.0
description: cert-manager per-namespace issuer setup
keywords:
  - cert-manager
home: https://github.com/Cray-HPE/cray-certmanager
sources:
  - https://github.com/jetstack/cert-manager
maintainers:
  - name: kburns-hpe
icon: https://github.com/jetstack/cert-manager/raw/master/logo/logo.png
appVersion: 0.14.1
