apiVersion: v2
name: cray-certmanager
version: 0.7.2
description: Support for managing PKI certificates and associated key material inside k8s
keywords:
  - cert-manager
home: https://github.com/Cray-HPE/cray-certmanager
sources:
  - https://github.com/jetstack/cert-manager
dependencies:
  - name: cert-manager
    version: v1.5.5
    repository: https://charts.jetstack.io
maintainers:
  - name: kburns-hpe
  - name: mitchty
icon: https://github.com/jetstack/cert-manager/raw/master/logo/logo.png
appVersion: 1.5.5
annotations:
  artifacthub.io/changes: |
    - kind: security
      description: Refactor to use patched CSM images
      links:
        - name: Github Issue
          url: https://github.com/Cray-HPE/cray-certmanager/issues/2
        - name: Github PR
          url: https://github.com/Cray-HPE/cray-certmanager/pull/3
  artifacthub.io/images: |
    - name: curl
      image: artifactory.algol60.net/csm-docker/stable/docker.io/curlimages/curl:7.80.0
    - name: cert-manager-cainjector
      image: artifactory.algol60.net/csm-docker/stable/quay.io/jetstack/cert-manager-cainjector:v1.5.5
    - name: cert-manager-ctl
      image: artifactory.algol60.net/csm-docker/stable/quay.io/jetstack/cert-manager-ctl:v1.5.5
    - name: cert-manager-controller
      image: artifactory.algol60.net/csm-docker/stable/quay.io/jetstack/cert-manager-controller:v1.5.5
    - name: cert-manager-webhook
      image: artifactory.algol60.net/csm-docker/stable/quay.io/jetstack/cert-manager-webhook:v1.5.5
  artifacthub.io/license: MIT
