# Required for the webhook certificate to match the 'cray' overlay service name
# Also updated in the cray-certmanager-init CRDs (*...webhookClientConfig.service instances)

# ExtraArgs (--enable-certificate-owner-ref=true) used to delete TLS key material (K8S secret)
# when certificate is deleted
# https://github.com/jetstack/cert-manager/pull/1828
curl:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/curlimages/curl
    tag: 7.80.0
    pullPolicy: IfNotPresent
webhookServiceName:
  serviceName: cray-certmanager-cert-manager-webhook
cert-manager:
  installCRDs: true

  global:
    logLevel: 6
    podSecurityPolicy:
      # Create PodSecurityPolicy for cert-manager.
      #
      # Note that PodSecurityPolicy was deprecated in Kubernetes 1.21 and removed in Kubernetes 1.25.
      enabled: true
      # Configure the PodSecurityPolicy to use AppArmor.
      useAppArmor: true

  image:
    registry: artifactory.algol60.net
    repository: csm-docker/stable/quay.io/jetstack/cert-manager-controller
    # tag defaults to appVersion
  replicaCount: 3
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - cert-manager
            topologyKey: kubernetes.io/hostname
  extraArgs:
    - "--enable-certificate-owner-ref=true"
  webhook:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/jetstack/cert-manager-webhook
      # tag defaults to appVersion
    replicaCount: 3
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 200Mi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - webhook
              topologyKey: kubernetes.io/hostname
  cainjector:
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/jetstack/cert-manager-cainjector
      # tag defaults to appVersion
    replicaCount: 3
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 200Mi
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - cainjector
              topologyKey: kubernetes.io/hostname
  startupapicheck:
    podAnnotations:
      "sidecar.istio.io/inject": "false"
    image:
      registry: artifactory.algol60.net
      repository: csm-docker/stable/quay.io/jetstack/cert-manager-startupapicheck
# Not actively ran just used in a k8s job to upgrade existing resources.
startupapicheck:
  image:
    registry: artifactory.algol60.net
    repository: csm-docker/stable/quay.io/jetstack/cert-manager-startupapicheck
