# Required for the webhook certificate to match the 'cray' overlay service name
# Also updated in the cray-certmanager-init CRDs (*...webhookClientConfig.service instances)

# ExtraArgs (--enable-certificate-owner-ref=true) used to delete TLS key material (K8S secret)
# when certificate is deleted
# https://github.com/jetstack/cert-manager/pull/1828
curl:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/docker.io/curlimages/curl
    tag: 7.80.0
    pullPolicy: IfNotPresent
cert-manager:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/quay.io/jetstack/cert-manager-controller
    # tag defaults to appVersion
  replicaCount: 3
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - cert-manager
            topologyKey: kubernetes.io/hostname
  extraArgs:
    - "--set=webhook.hostNetwork=true"
    - "--set=webhook.securePort=10260"
    - "--set=enable-certificate-owner-ref=true"
    - "--set=installCRDs=true"
    - "--set=startupapicheck.podAnnotations\\.sidecar\\.istio\\.io/inject=false"
  webhook:
    image:
      repository: artifactory.algol60.net/csm-docker/stable/quay.io/jetstack/cert-manager-webhook
      # tag defaults to appVersion
    replicaCount: 3
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - webhook
              topologyKey: kubernetes.io/hostname
    serviceName: cray-certmanager-cert-manager-webhook
  cainjector:
    image:
      repository: artifactory.algol60.net/csm-docker/stable/quay.io/jetstack/cert-manager-cainjector
      # tag defaults to appVersion
    replicaCount: 3
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - cainjector
              topologyKey: kubernetes.io/hostname
# Not actively ran just used in a k8s job to upgrade existing resources.
ctl:
  image:
    repository: artifactory.algol60.net/csm-docker/stable/quay.io/jetstack/cert-manager-ctl
    tag: v1.5.5
