name: Lint, test, and scan Helm charts
on:
  pull_request:
    branches:
      - master
      - release/**
  workflow_dispatch:
jobs:
  lint-test-scan:
    uses: Cray-HPE/workflows/charts/lint-test-scan.yaml@main
    with:
      charts-dir: kubernetes
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}
